### PR TITLE
Use actual network genesis constants (genesisTimestamp, slotTime, accountCreationFee).

### LINKED ISSUE #1366: genesisTimestamp is hardcoded to a wrong date
```typescript
  // copied from mina/genesis_ledgers/berkeley.json
  // TODO fetch from graphql instead of hardcoding
  const genesisTimestampString = '2023-02-23T20:00:01Z';
  const genesisTimestamp = UInt64.from(
    Date.parse(genesisTimestampString.slice(0, -1) + '+00:00')
  );
```
https://github.com/o1-labs/o1js/blob/main/src/lib/mina.ts#L742

### PR DESCRIPTION
**Pull request by shimkiv**
Closes #1366

### CODE REVIEW

**Comment by shimkiv** [comment]
It probably won't work since `getCachedGenesisConstants` won't wait for promise to resolve...

File: src/examples/fetch_live.ts [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+  archive: useCustomLocalNetwork
+    ? 'http://localhost:8282'
+    : 'https://api.minascan.io/archive/berkeley/v1/graphql',
+  lightnetAccountManager: 'http://localhost:8181',
+});
+Mina.setActiveInstance(network);
+const transactionFee = 100_000_000;
+
+// Fee payer setup
+console.log('');
```
Comment (Trivo25) [inline src/examples/fetch_live.ts:19]: empty console log

File: src/examples/fetch_live.ts [hunk 2]
```diff
@@ -0,0 +1,73 @@
+import { expect } from 'expect';
```
Comment (Trivo25) [inline src/examples/fetch_live.ts:1]: i think this file could use some spacing and line breaks

File: src/lib/mina.ts [hunk 3]
```diff
@@ -369,6 +372,11 @@ interface Mina {
 }
 
 const defaultAccountCreationFee = 1_000_000_000;
+const defaultNetworkConstants = {
+  genesisTimestamp: UInt64.from(0),
+  slotTime: UInt64.from(3 * 60 * 1000),
+  accountCreationFee: UInt64.from(defaultAccountCreationFee),
```
Comment (Trivo25) [inline src/lib/mina.ts:378]: do we need the account creation fee twice or can we simplify to only use one source?

**Review by Trivo25 — APPROVED** [review]
lgtm just a couple of nits!

File: src/lib/mina.ts (hunk 3 above)
Comment (shimkiv) [reply src/lib/mina.ts:378]: Maybe then we should:
1. Remove [accountCreationFee API](https://github.com/o1-labs/o1js/pull/1367/files#diff-1f92503aa572cd2ea7bc843e4e77809f3aef81f49bb25995a80d032127482ffcR749);
2. And allow return [default network constants](https://github.com/o1-labs/o1js/pull/1367/files#diff-1f92503aa572cd2ea7bc843e4e77809f3aef81f49bb25995a80d032127482ffcR375) instead of [throwing](https://github.com/o1-labs/o1js/pull/1367/files#diff-1f92503aa572cd2ea7bc843e4e77809f3aef81f49bb25995a80d032127482ffcR768);
3. Update all API usage (obviously).

WDYT?

File: src/examples/fetch_live.ts (hunk 2 above)
Comment (shimkiv) [reply src/examples/fetch_live.ts:1]: Will reformat it, thanks.

File: src/lib/mina.ts (hunk 3 above)
Comment (mitschabaude) [reply src/lib/mina.ts:378]: sounds good, but please deprecate the old API, not remove

**Review by Trivo25 — APPROVED** [review]
I think we should add the new API changes to the changelog, otherwise its good to go!

**Comment by shimkiv** [comment]
> I think we should add the new API changes to the changelog, otherwise its good to go!

Added one, thank you.

**Comment by shimkiv** [comment]
@Trivo25 @mitschabaude if all is good now then I'll merge later today.
