### PR TITLE
Fix build and run on Windows (+ additional benchmarks CI target platform).

### LINKED ISSUE #1502: Support benchmarks on Windows
https://github.com/o1-labs/o1js/pull/1498

### PR DESCRIPTION
**Pull request by shimkiv**
Although not sure if we need to benchmark on all 3 platforms (+ additional ARM arch in future).
Closes #1502

### CODE REVIEW

**Review by ymekuria — APPROVED** [review]

File: src/build/build-example.js [hunk 1]
```diff
@@ -2,14 +2,19 @@ import fs from 'fs/promises';
...
 export { buildAndImport, build, buildOne };
 
 async function buildAndImport(srcPath, { keepFile = false }) {
   let absPath = await build(srcPath);
   let importedModule;
   try {
-    importedModule = await import(absPath);
+    let absPathForImport = absPath
+    if (platform === 'win32') {
+      absPathForImport = 'file:///' + absPathForImport;
```
Comment (mitschabaude) [inline src/build/build-example.js:15]: Feels like the path should already be fixed in build() and buildOne()

File: src/build/run.js [hunk 2]
```diff
@@ -18,6 +19,9 @@ npx snarky-run [file]`);
 if (!bundle) {
   let absPath = await buildOne(filePath);
   console.log(`running ${absPath}`);
+  if (platform === 'win32') {
+    absPath = 'file:///' + absPath;
```
Comment (mitschabaude) [inline src/build/run.js:23]: Feels like the path should already be fixed in build() and buildOne()
